### ISSUE TITLE
request to support hackrf

### ISSUE THREAD

**Issue by SonyKucing** [martinmarinov/AndroidDvbDriver#1]
hello master.., it will nice if support hackrf,,, thanks,,

**Comment by martinmarinov** [comment]
Hey,

In theory I believe it should be possible to support hackrf via SDR for DVB-T. In practice I doubt Android devices will be able to do fast enough USB transfers and will have enough CPU for the task.

If someone writes a driver that works I would be happy to include it in the driver.

Martin
