### ISSUE TITLE
Please do not commit binaries into vcs

### ISSUE THREAD

**Issue by andreygursky** [martinmarinov/AndroidDvbDriver#2]
Please avoid putting binaries into git (https://github.com/martinmarinov/AndroidDvbDriver/blob/ece1ca74afd11da90f43715f21f78a0becbdea2f/app/app-release.apk). Use https://github.com/martinmarinov/AndroidDvbDriver/releases instead.

Thanks,
Andrey

**Comment by martinmarinov** [comment]
Hey Andrey, I don't see a big problem with that :) I am very rarely uploading binaries anyways. I will only upload a binary if it goes live on Google Play.

It's easier for me and saves time vs the manual release process.

**Comment by andreygursky** [comment]
> rarely uploading binaries anyways

Martin, thanks for clarifying.

**Comment by martinmarinov** [comment]
No worries :)
