### ISSUE TITLE
DVB-T2 - Which hardware? 

### ISSUE THREAD

**Issue by anonimo82** [martinmarinov/AndroidDvbDriver#36]
Hello everyone.
Which USB TV Receiver should I buy for DVB-T2 support?
Thanks in advance for any help.

**Comment by anonimo82** [comment]
@martinmarinov any help?

**Comment by anonimo82** [comment]
Note I'm looking for a USB TV Tuner which supports the DVB-T2 standard AND is compatible with Aerial TV

**Comment by martinmarinov** [comment]
From readme:

* RTL2832 with tuner chip R828D (DVB-T2 support for MN88473 and MN88472 devices)
* MyGica (Geniatech) T230C

The RTL2832 sticks are easier to find but are not as sensitive from my experience. This is a typical one https://alibaba.com/product/1820965313/Multi-Standards-dvb-t2-dvb-t.html

**Comment by anonimo82** [comment]
Thanks.
Will this work? https://www.amazon.it/dp/B01BU4UIOW/ref=cm_sw_r_cp_apa_glt_i_KGZR77J7V0PQFSC30P73

**Comment by martinmarinov** [comment]
I think the one you have linked should work.

**Comment by anonimo82** [comment]
Thanks a lot
