### ISSUE TITLE
How to read TS stream?

### ISSUE THREAD

**Issue by sdabet-tns** [martinmarinov/AndroidDvbDriver#4]
I successfully managed to pick device, set frequency and pids, and receive TS stream data. However I can't find any way to read that data. 

Here's what I tried (and failed):
- write stream data to a *.ts file and open it with VLC
- open "http://localhost:<transferPort\>" URL in VLC on the device

Do you have any input/suggestion on how to read the stream content?

**Comment by martinmarinov** [comment]
Hey,

Setting pids should be enough for you to play the transport stream in VLC.

You can use a tool such as Wireshark to inspect the content of the TS to confirm whether you have set the correct pids.

Martin
